### ISSUE TITLE
Inquiry About Code Availability

### ISSUE THREAD

**Issue by zebin-huang** [elena-ecn/mpc-cbf#1]
Hello,

I've reviewed the code and noticed that only Scenario 1's code is visible. I'm wondering if the code for the other sections is open source. I'd appreciate any information regarding their availability.

Thank you!

**Comment by elena-ecn** [comment]
Hi zebin-huang,

The code and parameters for all of the scenarios are available in the repo (except for the Gazebo simulations). You just need to select the scenario that you want in the config.py file (line 49).

**Comment by elena-ecn** [comment]
Hi zebin-huang,

The code and parameters for all of the scenarios are available in the repo (except for the Gazebo simulations). You just need to select the scenario that you want in the config.py file (line 49).

**Comment by zebin-huang** [comment]
Thank you so much for your prompt reply!
