### ISSUE TITLE
i need your help

### ISSUE THREAD

**Issue by Maple-ssx** [elena-ecn/mpc-cbf#2]
How can I use it in ros ?？

**Comment by dongjieHuo** [comment]
Hello i have same question.

**Comment by inshaandrabi** [comment]
Hi, I have the same query !

**Comment by elena-ecn** [comment]
Hi everyone! Thank you for your interest in this project. 

Although this part is not publicly available, if you are familiar with ROS, it should be fairly straightforward to implement.

The simplest way to do it, for known static obstacles, would be the following:

while goal not reached:

- Subscribe to the odometry data to get the current robot pose x
- Compute the optimal velocity input from the MPC controller u = mpc.make_step(x) 
- Publish the computed velocity (e.g., in the /cmd_vel topic) for the robot to move

**Comment by inshaandrabi** [comment]
u0 computed will be send as linear velocity? is angular velocity not required ?

**Comment by elena-ecn** [comment]
u0 is a two-dimensional vector. It consists of both the linear and angular velocities that need to be sent to the robot.

**Comment by inshaandrabi** [comment]
okay so, the message that would be send to the robot as linear.x and angular.z would be the sliced part of this vector u0?

**Comment by inshaandrabi** [comment]
After issuing the u0 to the robot, it moves only until the simulation graph shows.
